steps:

  # Build the AngularJS application
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Upload the compiled application files to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'dist/*', '$_BUCKET']
