steps:
  # Create a Google Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['storage', 'buckets', 'create', '[ihangularjs]', '--location', 'us']

  # Build the AngularJS application
  - name: 'node:12'
    entrypoint: npm
    args: ['install']
  - name: 'node:12'
    entrypoint: npm
    args: ['run', 'build']

  # Upload the compiled application files to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'dist/*', 'gs://[ihangularjs]/']

# Set up a trigger to automatically build and deploy the application
# when code is pushed to the repository
triggers:
  - github:
      repo-name: [interviewhelpio/angularjs.git]
      branch: master

# Enable static website hosting for the Google Cloud Storage bucket
# that contains the compiled application files
#resources:
#  archives:
#  - contents: dist
#    name: dist
#  - contents: cloudbuild.yaml
#    name: cloudbuild.yaml
#  - contents: gsutil.tar.gz
#    name: gsutil.tar.gz

# Replace [BUCKET_NAME] with the name of your Google Cloud Storage bucket
# Replace [LOCATION] with the location for the bucket (e.g. "us", "eu", "asia")
# Replace [REPO_NAME] with the name of your GitHub repository

